# ===========================
# NexusStock — Default Profile (H2 Dev DB)
# ===========================
spring.application.name=NexusStock

# MySQL Database (Aiven)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create   # <-- force table creation
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=${PORT:8080}
server.error.include-message=always

# Logging
logging.level.com.nexusstock=DEBUG
logging.level.org.hibernate.SQL=WARN
